version: "3.7"
services:
  server:
    build: .
    env_file: server/.env
    entrypoint: ${ENTRYPOINT} src/index
    volumes:
      - "./server:/server"
      - "build:/server/build"
      - "node_modules:/server/node_modules"

volumes:
  build:
  node_modules: