version: "3.7"
services:
  server:
    env_file: server/.env
    build: .
    image: server
    container_name: server
    restart: always
    entrypoint: ${ENTRYPOINT} src/index
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./server:/server"
      - "build:/server/build"
      - "node_modules:/server/node_modules"

volumes:
  build:
  node_modules: