version: "3.7"
services:
  server:
    build: 
      args:
        NODE_ENV: development
    volumes:
      - ./server/src:/server/src
    command: npx nodemon src/index

  nginx:
    volumes:
      - ./nginx.development.conf:/etc/nginx/nginx.conf