version: "3.7"
services:
  client:
    restart: always
    build:
      context: .
      dockerfile: client.dockerfile

  server:
    restart: always
    build:
      context: .
      dockerfile: server.dockerfile

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${CERT-./.gitignore}:/etc/letsencrypt/fullchain.pem
      - ${KEY-./.dockerignore}:/etc/letsencrypt/privkey.pem
    ports:
      - 80:80
      - 443:443