version: "3.7"
services:
  server:
    environment: 
      NODE_ENV: development
    build: 
      args:
        NODE_ENV: development
    ports:
      - "${HTTP_PORT-80}:3080"
    volumes:
      - "./server/src:/server/src"
    command: npx nodemon src/index