version: "3.7"
services:
  server:
    entrypoint: npx nodemon src/index
    environment: 
      NODE_ENV: development
    build: 
      args:
        NODE_ENV: development
    volumes:
      - "./server:/server"
      - "node_modules:/server/node_modules"
    ports:
      - "${PORT-80}:3000"

volumes:
  node_modules: