version: "3.7"
services:
  server:
    environment: 
      NODE_ENV: development
    build: 
      args:
        NODE_ENV: development
    command: npx nodemon src/index
    volumes:
      - "./server/src:/server/src"