version: "3.7"
services:
  server:
    env_file: server/.env
    build: .
    restart: always
    entrypoint: ${ENTRYPOINT-node} src/index
    volumes:
      - "./server:/server"
      - "build:/server/build"
      - "node_modules:/server/node_modules"

volumes:
  build:
  node_modules: