version: "3.7"
services:
  client:
    build:
      context: .
      dockerfile: client.dockerfile
    networks:
      - nginx

  server:
    build:
      context: .
      dockerfile: server.dockerfile
    networks:
      - nginx

  nginx:
    image: nginx:alpine
    networks:
      - nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

networks:
  nginx: