version: "3.7"
services:
  server:
    env_file: server/.env.development
    entrypoint: npx nodemon src/index
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - "./server:/server"
      - "node_modules:/server/node_modules"
    ports:
      - "${PORT-80}:3000"

volumes:
  node_modules: