FROM node:alpine as server
ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV
WORKDIR /server
RUN mkdir lib
RUN ln -s lib node_modules
COPY package*.json ./
RUN npm install
COPY . .

FROM node:alpine
ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV
COPY --from=server /server /server
WORKDIR /server
RUN npx tsc -b jsconfig.json

EXPOSE 3000

ENTRYPOINT []

CMD ["node", "-r", "dotenv/config", "lib/index"]