version: "3"
services:
  server:
    build: .
    image: server
    container_name: server
    entrypoint: ${ENTRYPOINT} src/index
    restart: always
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ".:/server"
      - "client:/client"
      - "node_modules:/server/node_modules"

volumes:
  client:
    external: true
  node_modules: