version: "3.7"
services:
  server:
    build: 
      args:
        NODE_ENV: development
    volumes:
      - ./src:/server/src
    command: npm run nodemon

  nginx:
    volumes:
      - ./nginx.development.conf:/etc/nginx/nginx.conf