version: "3.7"
services:
  server:
    restart: unless-stopped
    build: .

  nginx:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${KEY-./.dockerignore}:/etc/letsencrypt/privkey.pem
      - ${CERT-./.gitignore}:/etc/letsencrypt/fullchain.pem
    ports:
      - 80:80
      - 443:443